### ISSUE TITLE
FPS are fixed, but the game feels laggier?

### ISSUE THREAD

**Issue by fin-framilano** [shiversoftdev/t7patch#8] opened 2022-09-23 15:53 UTC
Frametimes are way weirder with this patch, I can see that something is wrong even if I'm reaching 140 fps, doesn't feel smooth at all.
Without using the patch is smooth though.

Any idea if what I'm saying makes any sense to you?

Anyway, great job and thank you for your work!

**Comment by shiversoftdev** [comment] 2022-09-23 16:33
Certain users are reporting frame issues near the start of games that tend to disappear after a couple of minutes. I am looking into this but at the moment I'm not sure of any specific root cause.

**Comment by Master-64** [comment] 2022-09-27 15:35
Seconding this, but the performance doesn't solve itself over time. The game feels like it's constantly micro-stuttering at times (very inconsistent). Now granted BO3 isn't that stable in the first place, but it's still worth figuring out (as you already said).

**Comment by shiversoftdev** [comment] 2023-01-06 15:07
Please check to see if this issue has been addressed in 1.08. Thank you.

**Comment by Master-64** [comment] 2023-01-25 07:55
Yes, the issue is definitely still there (v1.11).

**Comment by shiversoftdev** [comment] 2023-01-25 11:23
NikkMann did some investigation and was able to fix it by adjusting processor affinity down to four cores, then waiting a second and switching it back. Let me know if this works for you, and if so, it means I can just programmatically do it in the patch.

**Closed** 2023-01-29 21:08 UTC
